### ISSUE TITLE
Support Dynamic Type Changes

### ISSUE THREAD

**Issue by subdigital** [5calls/ios#144]
Currently the app doesn't respond to dynamic type changes. This is something we should fix to be more accessible.

A probably incomplete list of places that need this work:

- [x] Issue Detail
- [x] Call Scripts
- [x] About screen
- [x] Onboarding screens
- [x] Issue list (front page and more)
- [x] Impact
- [x] Reminders
- [x] Set location

**Comment by Abizern** [comment]
Related to this - How tied are we to using Roboto rather than the system font? This would be much smaller task if that were the case.

I realise that there may be issues about maintaining a consistent typeface across Web, Android and Mobile. I also realise that it is something of a personal bugbear of mine to use the Android system font on an iOS device.

Of course, this would mean making other related changes to the app and the css files used for serving stored web content. But the app is already a little inconsistent with the Welcome screen using the system font.

So it would make implementing this feature easier, and make the app look more native, at the cost of having to rework parts of the app and, maybe the design.

**Comment by nickoneill** [comment]
I'm happy to use the default for the platform for most text, particularly if it makes things simpler. The only case I really care about maintaining the font is in the logo which is generally not dynamically rendered anyway. We didn't pick Roboto (and technically it's Roboto Condensed) based on android, it was inherited from the logo usage when we were web only.

**Comment by Abizern** [comment]
I don't want to mess with the logo, and that's not something that's affected by this.

If a few more people come in on the same side I'll start work on it in a couple of days (unless someone else wants to take it). It's a good step for accessibility.

**Comment by subdigital** [comment]
+1 on native font

**Comment by iainsmith** [comment]
Hey All,

I've started diving into this. As we're supporting iOS 10 we can mostly get away with using 

`adjustsFontForContentSizeCategory = true // or set in storyboard`
`font = UIFont.preferredFont(forTextStyle: .body) // or set in storyboard`

I have a branch on my fork that I'll open up a WIP PR for.

# Screens updated

I'm going to leave a list of areas here to remind myself.

### IssueDetailViewController

* [x] CSS support for dynamic type
* [ ] Representatives title
* [ ] Representatives details

**Comment by nickoneill** [comment]
Do your two PRs handle all the cases for dynamic type @iainsmith?

**Comment by iainsmith** [comment]
Hey @nickoneil, there are a few screens that don’t have any support for dynamic type yet. We could leave this ticket open for a while or open new tickets that are specific to a screen.

**Comment by nickoneill** [comment]
Sounds great @iainsmith! You don't need to do all the dynamic type work yourself, but can you list the other screens here that need work so I can point folks in that direction?

**Comment by nickoneill** [comment]
I'm going to put out a release to fix the list stuff later tonight, moving the rest of the items here to 1.6

**Comment by heathermh** [comment]
with 2.0 release, the app supports dynamic text
