### ISSUE TITLE
Calling reason truncated on call script screen

### ISSUE THREAD

**Issue by alexanderjrobinson** [5calls/ios#30]
When the calling reason is more than 1 line the text is truncated. See screenshot.

![simulator screen shot feb 5 2017 7 50 19 pm](https://cloud.githubusercontent.com/assets/541991/22631488/792f9962-ebdc-11e6-935f-b1ccf2992daa.png)

**Comment by mccarron** [comment]
Darn that used to work. Investigating.

**Comment by mccarron** [comment]
Fixed in PR #31 
![simulator screen shot feb 5 2017 7 30 14 pm](https://cloud.githubusercontent.com/assets/45654/22631855/89b32392-ebd9-11e6-9a95-0ea34af5d980.png)

Even works on iPhone 5! 
![simulator screen shot feb 5 2017 7 32 09 pm](https://cloud.githubusercontent.com/assets/45654/22631887/d8e07b9a-ebd9-11e6-8c53-b187b2e52377.png)
