### ISSUE TITLE
Add phone numbers for local offices

### ISSUE THREAD

**Issue by armadsen** [5calls/ios#94]
I often call my representatives' local offices for a few reasons: 

- They're open later locally due to the time zone difference.
- Sometimes when the DC office voice mailbox is full, the local office's mailbox will not be (and vice versa).

It would be nice if 5Calls would show all office numbers for each representative, not just the DC offices. Not sure if the API being used provides this info.

**Comment by subdigital** [comment]
They do have local numbers for many offices. This was a largely manual effort coordinated by the team in the slack room. Which candidates do you not have numbers for?  If you want to gather them I can provide this info to the team that handles it.

**Comment by nickoneill** [comment]
We've got local numbers for senate + house, senate is coming through the API right now but the house numbers need a bit of cleanup before they're ready. This week probably.

**Comment by armadsen** [comment]
I see now that if you tap the "Line Busy?" button, additional numbers show up. I still don't see that button or additional numbers for my congress person:

![img_3846](https://cloud.githubusercontent.com/assets/1057175/23174485/c3c9e772-f819-11e6-8106-66ca625195d3.PNG)

**Comment by chrisbrandow** [comment]
Here is a layout that I just tested out that possibly clarifies the field office issue. I also found it hard to discover at first, even though I knew we had implemented the feature.

I can push it up as a PR if there is any interest in it.

1. I moved the button to be below the main phone number
2. I changed the text, though there might be better phrasing
3. Since this button now has longer text, I constrained it so that on smaller screens it will not crowd the avatar image
4. I removed the "Call This Office:" label, since it seems like a redundant instruction and the screen is already busy enough as it is.
5. I added a small transparent border to top of footerView for visual separation.

![callscriptviewcontroller adjustments](https://cloud.githubusercontent.com/assets/4108083/23272103/d1239d3c-f9ae-11e6-804a-06a399e915e9.png)

**Comment by subdigital** [comment]
Closing this, as it gets implemented server side.
